//! Conventional Commits parser using `winnow`.
//!
//! Grammar:
//!
//! ```text
//! header := kind ('(' scope ')')? '!'? ':' ' ' subject
//! kind   := 'feat' | 'fix' | 'refactor' | 'perf' | 'docs' | 'chore'
//!        |  'test' | 'ci'  | 'build'    | 'style' | 'revert'
//! scope  := [^)]+
//! body   := ... (scanned for `This reverts commit <sha>.`)
//! ```
//!
//! Commits auto-generated by `git revert` carry the header
//! `Revert "<original subject>"`; we recognise that shape as
//! synthetic `CommitKind::Revert`.

use compact_str::CompactString;
use knotch_kernel::event::{CommitKind, CommitRef};
use winnow::{
    ModalResult, Parser,
    ascii::space0,
    combinator::{alt, opt, preceded},
    error::{ContextError, ErrMode, StrContext},
    token::{take_till, take_while},
};

use crate::commit::ParsedCommit;

/// Parse a full commit message (subject + body) into a `ParsedCommit`.
///
/// # Errors
/// Returns `ParseError` if the header does not conform to the
/// conventional-commits grammar and is not a recognized synthetic
/// revert shape.
pub fn parse_commit_message(
    sha: CommitRef,
    message: &str,
) -> Result<ParsedCommit, ParseError> {
    let (subject, body) = split_subject_body(message);
    let header = ParsedHeader::try_parse(subject)?;

    let breaking = header.breaking || body_has_breaking_footer(body);
    let reverts = extract_revert_target(body, &header);

    Ok(ParsedCommit {
        sha,
        kind: header.kind,
        scope: header.scope,
        breaking,
        subject: CompactString::from(subject),
        body: CompactString::from(body),
        reverts,
    })
}

/// Error taxonomy for header parsing.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[non_exhaustive]
pub enum ParseError {
    /// Header did not match the grammar and is not a synthetic revert.
    #[error("header does not match conventional-commits grammar: {0:?}")]
    InvalidHeader(String),
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ParsedHeader {
    kind: CommitKind,
    scope: Option<CompactString>,
    breaking: bool,
}

impl ParsedHeader {
    fn try_parse(subject: &str) -> Result<Self, ParseError> {
        // Try a synthetic revert header first.
        if let Some(stripped) = subject.strip_prefix("Revert \"") {
            if stripped.ends_with('"') {
                return Ok(Self {
                    kind: CommitKind::Revert,
                    scope: None,
                    breaking: false,
                });
            }
        }

        let mut input = subject;
        match conventional_header.parse_next(&mut input) {
            Ok(parsed) => {
                if !input.is_empty() {
                    // Extra trailing content after the subject rule —
                    // still count as match; the subject captured the
                    // rest via `take_till`.
                }
                Ok(parsed)
            }
            Err(_) => Err(ParseError::InvalidHeader(subject.to_owned())),
        }
    }
}

fn conventional_header(input: &mut &str) -> ModalResult<ParsedHeader> {
    let kind = parse_kind
        .context(StrContext::Label("kind"))
        .parse_next(input)?;
    let scope = opt(parse_scope)
        .context(StrContext::Label("scope"))
        .parse_next(input)?;
    let breaking = opt('!').parse_next(input)?.is_some();
    ':'.parse_next(input)?;
    space0.parse_next(input)?;
    // Consume the rest of the subject; the caller keeps the original
    // subject as the display string.
    let _ = take_till(0.., ['\r', '\n']).parse_next(input)?;
    Ok(ParsedHeader { kind, scope, breaking })
}

fn parse_kind(input: &mut &str) -> ModalResult<CommitKind> {
    alt((
        "feat".value(CommitKind::Feat),
        "fix".value(CommitKind::Fix),
        "refactor".value(CommitKind::Refactor),
        "perf".value(CommitKind::Perf),
        "docs".value(CommitKind::Docs),
        "chore".value(CommitKind::Chore),
        "test".value(CommitKind::Test),
        "ci".value(CommitKind::Ci),
        "build".value(CommitKind::Build),
        "style".value(CommitKind::Style),
        "revert".value(CommitKind::Revert),
    ))
    .parse_next(input)
}

fn parse_scope(input: &mut &str) -> ModalResult<CompactString> {
    preceded('(', scope_body_close).parse_next(input)
}

fn scope_body_close(input: &mut &str) -> ModalResult<CompactString> {
    let inner = take_while(0.., |c: char| c != ')')
        .parse_next(input)?;
    ')'.parse_next(input).map_err(|_: ErrMode<ContextError>| ErrMode::Backtrack(ContextError::new()))?;
    Ok(CompactString::from(inner))
}

fn split_subject_body(message: &str) -> (&str, &str) {
    let mut lines = message.splitn(2, '\n');
    let subject = lines.next().unwrap_or("");
    let rest = lines.next().unwrap_or("");
    // Conventional-commits requires a blank line between subject and
    // body; accept missing blank line gracefully.
    let body = rest.trim_start_matches('\n');
    (subject, body)
}

fn body_has_breaking_footer(body: &str) -> bool {
    body.lines().any(|line| {
        let trimmed = line.trim_start();
        trimmed.starts_with("BREAKING CHANGE:") || trimmed.starts_with("BREAKING-CHANGE:")
    })
}

fn extract_revert_target(body: &str, header: &ParsedHeader) -> Option<CommitRef> {
    // Pattern: "This reverts commit <sha>." anywhere in the body.
    // `header` is provided so the parser can prefer to apply this
    // only when the commit is plausibly a revert.
    let candidate = body.lines().find_map(|line| {
        let trimmed = line.trim();
        let after = trimmed.strip_prefix("This reverts commit ")?;
        let after = after.strip_suffix('.').unwrap_or(after);
        let sha: String = after.chars().take_while(|c| c.is_ascii_hexdigit()).collect();
        if sha.len() >= 7 { Some(sha) } else { None }
    })?;
    // If the header already identifies this as a Revert, accept the
    // body link unconditionally. Otherwise accept it too — many
    // projects emit ``fix: ...`` commits that cite ``This reverts...``
    // manually.
    let _ = header;
    Some(CommitRef::new(candidate))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sha() -> CommitRef {
        CommitRef::new("abc1234567890abcdef1234567890abcdef12345")
    }

    #[test]
    fn parses_feat_with_scope() {
        let parsed = parse_commit_message(sha(), "feat(auth): add OIDC login\n").expect("parse");
        assert_eq!(parsed.kind, CommitKind::Feat);
        assert_eq!(parsed.scope.as_deref(), Some("auth"));
        assert!(!parsed.breaking);
        assert_eq!(parsed.subject.as_str(), "feat(auth): add OIDC login");
    }

    #[test]
    fn parses_breaking_via_bang() {
        let parsed = parse_commit_message(sha(), "refactor!: drop v0 api\n").expect("parse");
        assert_eq!(parsed.kind, CommitKind::Refactor);
        assert!(parsed.breaking);
    }

    #[test]
    fn parses_breaking_footer_in_body() {
        let msg = "feat: add api\n\nBody line.\n\nBREAKING CHANGE: old API removed\n";
        let parsed = parse_commit_message(sha(), msg).expect("parse");
        assert!(parsed.breaking);
    }

    #[test]
    fn detects_synthetic_revert_header() {
        let parsed = parse_commit_message(
            sha(),
            "Revert \"feat: add thing\"\n\nThis reverts commit 0123456.\n",
        )
        .expect("parse");
        assert_eq!(parsed.kind, CommitKind::Revert);
        assert_eq!(parsed.reverts.as_ref().map(|s| s.as_str().to_owned()),
                   Some("0123456".to_owned()));
    }

    #[test]
    fn detects_manual_revert_body() {
        let parsed = parse_commit_message(
            sha(),
            "fix: undo buggy change\n\nThis reverts commit deadbee.\n",
        )
        .expect("parse");
        assert_eq!(parsed.kind, CommitKind::Fix);
        assert_eq!(parsed.reverts.as_ref().map(|s| s.as_str().to_owned()),
                   Some("deadbee".to_owned()));
    }

    #[test]
    fn rejects_non_conventional_header() {
        let err = parse_commit_message(sha(), "tweak things").unwrap_err();
        assert!(matches!(err, ParseError::InvalidHeader(_)));
    }

    #[test]
    fn accepts_empty_scope_parens() {
        let parsed = parse_commit_message(sha(), "feat(): trivial\n").expect("parse");
        assert_eq!(parsed.scope.as_deref(), Some(""));
    }
}
